services:
  postgres:
    image: postgres:16-alpine
    container_name: artha_postgres
    restart: always
    environment:
      POSTGRES_DB: artha_db
      POSTGRES_USER: artha_user
      POSTGRES_PASSWORD: artha_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
